import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/navbar";
import { ThemeProvider } from "@/components/Provider/ThemeProvider";
import { ModalProvider } from "@/components/providers/modal-provider";
import { ClerkProvider } from '@clerk/nextjs'

import React, { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          {/* <ThemeProvider attribute="class" defaultTheme="light"> */}
          <ThemeProvider attribute="class" defaultTheme="light">
            <ModalProvider/>
              {children}
          </ThemeProvider>
          {/* </ThemeProvider> */}
        </body>
      </html>
    </ClerkProvider>
    
  );
}
